// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaPoshtaProject.Data;

#nullable disable

namespace NewPoshtaProjectCore_1.Migrations
{
    [DbContext(typeof(NovaPoshtaDbContext))]
    [Migration("20250125093356_Add_tbl_Area")]
    partial class Add_tbl_Area
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("NovaPoshtaProjectCore.Models.Area", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ref");

                    b.ToTable("tbl_Area");
                });

            modelBuilder.Entity("NovaPoshtaProjectCore.Models.City", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreaRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ref");

                    b.HasIndex("AreaRef");

                    b.ToTable("tbl_City");
                });

            modelBuilder.Entity("NovaPoshtaProjectCore.Models.Warehouse", b =>
                {
                    b.Property<string>("Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfWarehouse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ref");

                    b.HasIndex("CityRef");

                    b.ToTable("tbl_Warehouse");
                });

            modelBuilder.Entity("NovaPoshtaProjectCore.Models.City", b =>
                {
                    b.HasOne("NovaPoshtaProjectCore.Models.Area", "Area")
                        .WithMany("Cities")
                        .HasForeignKey("AreaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("NovaPoshtaProjectCore.Models.Warehouse", b =>
                {
                    b.HasOne("NovaPoshtaProjectCore.Models.City", "City")
                        .WithMany("Warehouses")
                        .HasForeignKey("CityRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("NovaPoshtaProjectCore.Models.Area", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("NovaPoshtaProjectCore.Models.City", b =>
                {
                    b.Navigation("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
